### ISSUE TITLE
6.7版本已出

### ISSUE THREAD

**Issue by zopn333** [monoglo/InfernalMobs-CN#1]
求大佬来更新一下分支吧~

**Comment by monoglo** [comment]
作者只更新了 jar 文件，没有更新[源码](https://bitbucket.org/Eliminator/infernalmobs/src/master/)，作者不发的话没办法做到一致，反编译则是下下策
因为6.7版本只更新了1.19支持，没有其他变化，我在尝试手动升级

**Comment by monoglo** [comment]
已经升级到 [1.19](https://github.com/monoglo/InfernalMobs-CN/releases/tag/1.19.x) 了，因为作者没放源码，可能和作者写的不太一样
