### ISSUE TITLE
The New Issues is version of update.

### ISSUE THREAD

**Issue by ghost** [monoglo/InfernalMobs-CN#2]
尊敬的作者:
    您好,很荣幸能使用到您之前汉化过的插件，但是Infernal Mobs插件的版本现在已经更新到6.7.5了，如果可以的话，我希望您能继续跟进。
   此致
  敬礼                                                                                                                                                                   - HopeLight

**Comment by monoglo** [comment]
你好，因为工作较忙，直到现在才发现 issue。

作者在我去年6月跟进6.7版本之后，源码只放出了[两个commit](https://bitbucket.org/Eliminator/infernalmobs/commits/)，这两个新的commit都没有涉及新内容，都是bug修复，而且修复的大部分bug在我汉化时就顺带修复了。

也就是说，现在汉化插件的6.7版本和上游的6.7.5版本**几乎没有差别**。

如果汉化插件本身没有问题的话，我想等作者有内容更新后再合并，避免差异过大。_（可能，等到6.8版本？）_

**Comment by ghost** [comment]
好的，谢谢您的回复！

**Comment by monoglo** [comment]
因为作者支持了 1.20.x，现已同步到 [6.7.6](https://github.com/monoglo/InfernalMobs-CN/releases/tag/1.20.x)
